sonar.projectKey=api_crisiview
sonar.projectName=API CrisisView
sonar.sources=.
sonar.exclusions=node_modules/**,__tests__/**,coverage/**
sonar.tests=__tests__
sonar.javascript.lcov.reportPaths=coverage/lcov.info
